### ISSUE TITLE
Documentation needed: Contributor's Guide

### ISSUE THREAD

**Issue by erogluorhan** [NCAR/projectraijin.github.io#4]
**Description**
We need to put together a Contributor's Guide for the developers and collaborators of Raijin. However, it needs to be done in a way to complement each other with Uxarray's (which is not put together yet either)

**Links to other examples, if applicable**
[GeoCAT's Contributor's Guide](https://geocat.ucar.edu/pages/contributing.html)

**Comment by anissa111** [comment]
Close as not needed, as we're going to link directly to UXarray's Guide (https://github.com/NCAR/projectraijin.github.io/pull/11)
