### ISSUE TITLE
Publish coordinates for monthly standing meeting

### ISSUE THREAD

**Issue by clyne** [NCAR/projectraijin.github.io#7]
To facilitate community involvement we need to publish the Google Meets coordinates for our standing meeting. 

Question: if we're encouraging outside participation, should we move to zoom?

**Comment by jukent** [comment]
I'm going to take a look at this.

**Comment by clyne** [comment]
What do you think about putting it at the bottom of the home page (with a link from the contributing page)? Here is my thinking: "contributing" can be off putting. People may think they have to do something that they don't have time for. So those people may never click on the contributing link. But an open meeting on the - on the home page where everyone lands - may be more inviting for people who just want to drop in and listen.  

Of course we call also just add it on the contributing page, and maybe add blurb on the home page welcoming people to attend the open meeting.

**Comment by clyne** [comment]
> 

Sounds good. Thanks!

**Comment by jukent** [comment]
Orhan suggested putting it on the contact us page. Should I do all 3 places?

**Comment by clyne** [comment]
I think hosting it on the contact us page, and putting a short "join our open meeting" blurb with a link to the calendar on the contact us page would cover all of the bases:-)

**Comment by jukent** [comment]
You said "contact us" page twice. Did you mean contact us and contributing? or contact us and index?

**Comment by clyne** [comment]
Whoops. Sorry, I meant links on the "contributing" and home page.

**Comment by jukent** [comment]
@clyne since your selected page differs from @erogluorhan I'm discussing with the geocat team now

**Comment by jukent** [comment]
The consensus is home page and contact us.

**Comment by clyne** [comment]
Ok. But I thought we were in agreement. All good
